import os
from bhakti_study.constants import *

# Root directory
ROOT_DIR = ROOT_DIR_KEY

# Dataset path (raw data)
DATASET_PATH = os.path.join(ROOT_DIR, DATA_DIR)

# Paths to raw CSV files
CONTENT_DATA_FILE_PATH = os.path.join(ROOT_DIR, CONTENT_DATA_FILE)
LABELS_DATA_FILE_PATH = os.path.join(ROOT_DIR, LABELS_DATA_FILE)
TEST_DATA_FILE_PATH   = os.path.join(ROOT_DIR, TEST_DATA_FILE)

# Example of a processed data path
PROCESSED_DATA_FILE = os.path.join("data", "processed", "processed_data.csv")
PROCESSED_DATA_FILE_PATH = os.path.join(ROOT_DIR, PROCESSED_DATA_FILE)

# Example artifact directory usage
RAW_FILE_PATH = os.path.join(
    ROOT_DIR, ARTIFACT_DIR_KEY, DATA_INGESTION_KEY, CURRENT_TIME_STAMP,
    DATA_INGESTION_RAW_DATA_DIR, CONTENT_DATA_FILE
)

TRAIN_FILE_PATH = os.path.join(
    ROOT_DIR, ARTIFACT_DIR_KEY, DATA_INGESTION_KEY, CURRENT_TIME_STAMP,
    DATA_INGESTION_INGESTED_DATA_DIR, TRAIN_DATA_DIR_KEY
)

TEST_FILE_PATH = os.path.join(
    ROOT_DIR, ARTIFACT_DIR_KEY, DATA_INGESTION_KEY, CURRENT_TIME_STAMP,
    DATA_INGESTION_INGESTED_DATA_DIR, TEST_DATA_DIR_KEY
)

# (Optional) Data transformation paths
PREPROCESSING_OBJ_FILE = os.path.join(
    ROOT_DIR, ARTIFACT_DIR_KEY, DATA_TRANSFORMATION_ARTIFACT,
    DATA_PREPROCCED_DIR, DATA_TRANSFORMTION_PROCESSING_OBJ
)

TRANSFORM_TRAIN_FILE_PATH = os.path.join(
    ROOT_DIR, ARTIFACT_DIR_KEY, DATA_TRANSFORMATION_ARTIFACT,
    DATA_TRANSFORM_DIR, TRANSFORM_TRAIN_DIR_KEY
)

TRANSFORM_TEST_FILE_PATH = os.path.join(
    ROOT_DIR, ARTIFACT_DIR_KEY, DATA_TRANSFORMATION_ARTIFACT,
    DATA_TRANSFORM_DIR, TRANSFORM_TEST_DIR_KEY
)
